site_name: DenMune Docs
site_url: https://www.docs.zerobytes.one/
repo_url: https://github.com/egy1st/denmune-docs
copyright: An open source clustering algorithm  offered to you by Mohamed Abbas

nav:
    - Home: index.md
    - Installation: installation.md
    - Kaggle: kaggle/index.md
    - Examples: examples/index.md
    - Characteristics: characteristics/index.md
   
    
site_dir: public
edit_uri: edit/main/docs/
    
theme:
    name: mkdocs
    nav_style: primary
    locale: en
    include_sidebar: true
    collapse_navigation: false
    
    
markdown_extensions:
  - toc
  - abbr
  - admonition
  - attr_list
  - toc
    