[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DenMune Clustering Algorithm Documentation"
authors = [{name = "Mohamed Abbas", email = "mohamed.alyabbas@outlook.com"}]
dynamic = ["version", "description"]
